### ISSUE TITLE
Problem with app

### ISSUE THREAD

**Issue by sdillomatt** [sebastianfromearth/facepunch#1]
Hi,
i clone the repository, create virtualenv and pip install requirements.
launching the app i have this error

```
facepunch$ pip list
argparse (1.2.1)
blinker (1.4)
contextlib2 (0.5.4)
eventlet (0.17.4)
Flask (0.10.1)
greenlet (0.4.10)
gunicorn (19.3.0)
importlib (1.0.3)
itsdangerous (0.24)
Jinja2 (2.8)
MarkupSafe (0.23)
meld3 (1.0.2)
opbeat (3.1.1)
pip (1.5.6)
raven (5.27.1)
requests (1.1.0)
setuptools (5.5.1)
supervisor (3.1.3)
uuid (1.30)
Werkzeug (0.11.11)
wsgiref (0.1.2)
```

this the error

```
facepunch$ python index.py
Traceback (most recent call last):
  File "index.py", line 11, in <module>
    from creds import log_path, requests_verify_ssl, opbeat_organisation_id, opbeat_app_id, opbeat_secret_token, sentry_dsn, travisci_token
ImportError: No module named creds

```

i pip install creds

```
facepunch$ python index.py
Traceback (most recent call last):
  File "index.py", line 11, in <module>
    from creds import log_path, requests_verify_ssl, opbeat_organisation_id, opbeat_app_id, opbeat_secret_token, sentry_dsn, travisci_token
ImportError: cannot import name log_path

```

can you help me?

**Comment by sebastianfromearth** [comment]
Hi sdillomatt, sure, I can help you.
You need to create a file in the same directory as the other files in this project.
Call it 'creds.py'

Inside this file, assign some variables with names:
`log_path = /path/to/some/logfile/you/want
requests_verify_ssl = True/False
opbeat_organisation_id = ...
opbeat_app_id = ...
opbeat_secret_token = ...
sentry_dsn = ...
travisci_token = ...`

log_path is pretty self explanatory. 
requests_verify_ssl is for if you are using https or not, I used it to have one place to replace the ssl option in the requests library: http://docs.python-requests.org/en/master/

The rest are for some monitoring and build services I use. 
https://opbeat.com/
https://sentry.io
https://travis-ci.org/

If you don't use these, or don't want to use these, remove these lines from the code:
Lines 32 & 33 for the opbeat/sentry stuff
Lines 113 to 142 for the travisci stuff

Hope this helps. Sorry it wasn't more clear.

**Comment by sdillomatt** [comment]
yes i solved removing the line but the application don't work :(

**Comment by sebastianfromearth** [comment]
errors are written to the error logs in /var/log/gunicorn
if the flask error log doesnt exist (the one you name the path to in the creds.py file), make sure to create it.

**Comment by sdillomatt** [comment]
ok. now it works.... i made a edit: in the ajax.js when pass the option of request i change the url from your domain face-pun.ch to localhost:5000 :dancing_women: 
now it works :dancer:

**Comment by sebastianfromearth** [comment]
ahhhh right! i think I shall add all of this stuff to a readme so in future, other people can get it working without all the fuss. 
cheers buddy
